---
- hosts: ftphubdr
  user: ftpmstr 
  gather_facts: yes


# check latest version and exists already 
# stop the latest if running
# convert ini file to mpve to live
# stop live version 
# mv link to latest version ( unlink old ) 
# restart the new server 
# check ports are running


  pre_tasks: 
  - name: get latest version 
    raw:  curl   https://download.sftpplus.com/sftpplus/LATEST > version 
    delegate_to: 127.0.0.1

  vars:
    VERSION: "{{ lookup('file', '/home/vagrant/playbooks/version') }}"
    SFTPHOME: /ama/PRD/sftpplus

  tasks:
  - debug: 
      msg: "Version is : {{ VERSION }} "

  - name: set major version 
    set_fact:
     MAJOR: "{{ VERSION.split('.')[0] }}"
  - debug:
     msg: " MAJOR version is {{ MAJOR }}" 
    delegate_to: 127.0.0.1
    run_once: True


  - name: Set minor version 
    set_fact:
     MINOR: "{{ VERSION.split('.')[1] }}"
  - debug:
     msg: " Minor version os {{ MINOR }} " 
    delegate_to: 127.0.0.1
    run_once: True

  - name: check if latest version is installed - does the direcoty exist 
    stat:
      path: "{{ SFTPHOME }}/SFTPPLUS_{{ MAJOR }}.{{ MINOR }}.0"
    register: latestinstalled
  - meta: end_play
    when: latestinstalled.stat.isdir is not defined
  - debug:
      msg: "Latest version is {{ MAJOR }}.{{ MINOR }}.0 " 
      
  - name: parse the ini file with new values for server name
    lineinfile:
      path: "{{ SFTPHOME }}/SFTPPLUS_{{ MAJOR }}.{{ MINOR }}.0/configuration/server.ini"
      line: "name = {{ ansible_hostname }}"
      regexp: "name = {{ ansible_hostname }}-{{ MAJOR }}.{{ MINOR }}.0" 
    lineinfile:
       path: "{{ SFTPHOME }}/SFTPPLUS_{{ MAJOR }}.{{ MINOR }}.0/configuration/server.ini"
       line: "port = 15022"
       regexp: "15032" 
    tags:
      parser


  - name:  get process to kill for latest version
    raw : "cat {{ SFTPHOME }}/SFTPPLUS_{{ MAJOR }}.{{ MINOR }}.0/run/server.pid  " 
    register: result
    ignore_errors: True
  - shell: "kill -9 {{ result.stdout }} "
    ignore_errors: True 
  - debug: 
     var: result.stdout

  - name: check port is now stopped on 15032 
    wait_for:
     port: 15032
     delay: 4
     timeout: 10
     state: absent

  - name:  get process to kill for live version 
    raw : "cat {{ SFTPHOME }}/SFTPPlus/log/sftpplus.pid " 
    register: result
    ignore_errors: True
  - shell: "{{ SFTPHOME }}/etc/sftpplus_startstop force-stop"
    ignore_errors: True 
  - debug: 
     var: result.stdout

  - name: check port is now stopped on 15022 
    wait_for:
     port: 15022
     delay: 4
     timeout: 10
     state: absent

  - name: get current live version 
    shell: " find {{ SFTPHOME }}  -maxdepth 1 -type l -name SFTPPlus -ls | awk '{print $13}'  " 
    register: latestsymlink
  - debug: 
     msg: " Latest link is {{ latestsymlink.stdout }}"  

  - name: reconfigure migrated version ini file 
    command: "grep flrctdr03 {{SFTPHOME }}/{{ latestsymlink.stdout }}/configuration/server.ini"
    register: check
  - debug: 
     var: check
    

  - name: unlink existing SFTPLUS
    file: 
     dest: "{{ SFTPHOME }}/SFTPPlus"
     state: absent
     force: yes
  - name: link in new version 
    file:
      path: "{{ SFTPHOME }}" 
      src: "SFTPPLUS_{{ MAJOR }}.{{ MINOR }}.0"
      dest: "{{ SFTPHOME }}/SFTPPlus"
      state: link

  - name: restart new server 
    shell: "{{ SFTPHOME }}/etc/sftpplus_startstop start "
    ignore_errors: True

  - name: check latest is runing on 15022
    wait_for:
     port: 15022
     delay: 4
     timeout: 10
     state:  started





    

  







