---
- hosts: localhost
  become: yes
  gather_facts: no

  tasks: 
  - name: install htppd
    package: name=httpd state=installed
    
  - name: Pausing
    pause:
     prompt: Press any key to continue

  - name: Install lynx
    package: name=lynx state=installed

 
