---
- hosts: ftphubdr
  user: ftpmstr 
  gather_facts: no

  pre_tasks: 
  - name: get latest version 
    raw:  curl   https://download.sftpplus.com/sftpplus/LATEST > version 
    #shell:  VERSION=$( curl   https://download.sftpplus.com/sftpplus/LATEST)
    delegate_to: 127.0.0.1
    

  vars:
    VERSION: "{{ lookup('file', '/home/vagrant/playbooks/version') }}"
    SFTPHOME: /ama/PRD/sftpplus

  tasks:
  - debug: 
      msg: "Version is : {{ VERSION }} "

  - name: set major version 
    set_fact:
     MAJOR: "{{ VERSION.split('.')[0] }}"
  - debug:
     msg: " MAJOR version is {{ MAJOR }}" 
    delegate_to: 127.0.0.1
    run_once: True


  - name: Set minor version 
    set_fact:
     MINOR: "{{ VERSION.split('.')[1] }}"
  - debug:
     msg: " Minor version os {{ MINOR }} " 
    delegate_to: 127.0.0.1
    run_once: True

  - name: get the latest download
    get_url:
      url:  "http://download.sftpplus.com/sftpplus/{{ MAJOR }}/{{ MINOR }}/sftpplus-sles11-x64-{{ MAJOR }}.{{ MINOR }}.0.tar.gz" 
      dest: /tmp 
      mode: 0644
    delegate_to: 127.0.0.1
    run_once: True

  - name: copy file to remote server 
    copy: 
      src: /tmp/sftpplus-sles11-x64-{{ MAJOR }}.{{ MINOR }}.0.tar.gz 
      dest: /ama/PRD/sftpplus

  - name: unpack image 
    shell: "gunzip -dc /ama/PRD/sftpplus/sftpplus-sles11-x64-{{ MAJOR }}.{{ MINOR }}.0.tar.gz | tar -xf - "
    args:
       chdir: /ama/PRD/sftpplus

  - name: mv to unpacked directory to new name and remove any existing server.ini
    #file: "{{ item }}"
    #file: path='{{ SFTPHOME }}/SFTPPLUS_{{ MAJOR }}.{{ MINOR }}.0' state=absent
    copy:  remote_src=yes src='{{ SFTPHOME }}/sftpplus-sles11-x64-{{ MAJOR }}.{{ MINOR }}.0' dest='{{ SFTPHOME }}/SFTPPLUS_{{ MAJOR }}.{{ MINOR }}.0'
    #with_items:
    #  - path='{{ SFTPHOME }}/SFTPPLUS_{{ MAJOR }}.{{ MINOR }}.0' state=absent
    #  - src='{{ SFTPHOME }}/sftpplus-sles11-x64-{{ MAJOR }}.{{ MINOR }}.'0' path='{{ SFTPHOME }}/SFTPPLUS_{{ MAJOR }}.{{ MINOR }}.0 state=hard'
    #  - path='{{ SFTPHOME }}/SFTPPLUS_{{ MAJOR }}.{{ MINOR }}.0/configuration/server.ini' state=absent

  - name: initialise sftpplus
    command: ./bin/admin-commands.sh initialize
    args:
      chdir: "/ama/PRD/sftpplus/SFTPPLUS_{{ MAJOR }}.{{ MINOR }}.0"

  - name: Copy template server.ini into correct place
    copy: "remote_src=yes force=yes  src=/ama/PRD/sftpplus/custom/server.ini.template dest=/ama/PRD/sftpplus/SFTPPLUS_{{ MAJOR }}.{{ MINOR }}.0/configuration/server.ini owner=ftpmstr"

  







