---
- hosts: ftphubdr
  user: ftpmstr 
  gather_facts: yes

  pre_tasks: 
  - name: get latest version 
    raw:  curl   https://download.sftpplus.com/sftpplus/LATEST > version 
    delegate_to: 127.0.0.1

  vars:
    VERSION: "{{ lookup('file', '/home/vagrant/playbooks/version') }}"
    SFTPHOME: /ama/PRD/sftpplus

  tasks:
  - debug: 
      msg: "Version is : {{ VERSION }} "

  - name: set major version 
    set_fact:
     MAJOR: "{{ VERSION.split('.')[0] }}"
  - debug:
     msg: " MAJOR version is {{ MAJOR }}" 
    delegate_to: 127.0.0.1
    run_once: True


  - name: Set minor version 
    set_fact:
     MINOR: "{{ VERSION.split('.')[1] }}"
  - debug:
     msg: " Minor version os {{ MINOR }} " 
    delegate_to: 127.0.0.1
    run_once: True

  - name: get the latest download
    get_url:
      url:  "http://download.sftpplus.com/sftpplus/{{ MAJOR }}/{{ MINOR }}/sftpplus-sles11-x64-{{ MAJOR }}.{{ MINOR }}.0.tar.gz" 
      dest: /tmp 
      mode: 0644
    delegate_to: 127.0.0.1
    run_once: True

  - name: copy file to remote server 
    copy: 
      src: /tmp/sftpplus-sles11-x64-{{ MAJOR }}.{{ MINOR }}.0.tar.gz 
      dest: "{{ SFTPHOME }}"

  - name: unpack image 
    shell: "gunzip -dc {{ SFTPHOME }}/sftpplus-sles11-x64-{{ MAJOR }}.{{ MINOR }}.0.tar.gz | tar -xf - "
    args:
       chdir: "{{ SFTPHOME }}"

  - name: mv to unpacked directory to new name and remove any existing server.ini
    command: "{{ item }}"
    with_items:
      - 'rm -rf {{ SFTPHOME }}/SFTPPLUS_{{ MAJOR }}.{{ MINOR }}.0' 
      - 'mv {{ SFTPHOME }}/sftpplus-sles11-x64-{{ MAJOR }}.{{ MINOR }}.0 {{ SFTPHOME }}/SFTPPLUS_{{ MAJOR }}.{{ MINOR }}.0'
      - 'rm -rf {{ SFTPHOME }}/SFTPPLUS_{{ MAJOR }}.{{ MINOR }}.0/configuration/server.ini'

  - name: initialise sftpplus
    command: ./bin/admin-commands.sh initialize
    args:
     chdir: "{{ SFTPHOME }}/SFTPPLUS_{{ MAJOR }}.{{ MINOR }}.0"

  - name: Copy template server.ini into correct place
    copy: 
      remote_src: yes 
      force: yes 
      src: "{{ SFTPHOME }}/custom/server.ini.template" 
      dest: "{{ SFTPHOME }}/SFTPPLUS_{{ MAJOR }}.{{ MINOR }}.0/configuration/server.ini" 
      owner: ftpmstr

  - name: parse the ini file with new values
    lineinfile:
      path: "{{ SFTPHOME }}/SFTPPLUS_{{ MAJOR }}.{{ MINOR }}.0/configuration/server.ini"
      line: "name = {{ ansible_hostname }}-{{ MAJOR }}.{{ MINOR }}.0"
      regexp: :server:-latest
    tags:
      parser

  - name:  start the server 
    command: ./bin/admin-commands.sh start
    args:
      chdir: "{{ SFTPHOME }}/SFTPPLUS_{{ MAJOR }}.{{ MINOR }}.0"

  - name: check port is now running on 15032
    wait_for:
     port: 15032
     delay: 4
     timeout: 10
     state: started 



    

  







