---
- hosts: localhost
  become: yes
  gather_facts: no

  tasks: 
  - name: install tomcat
    package: name=tomcat state=present
  
  - name: Wait_for port 8080
    wait_for:
      port: 80
      state: started

  - name: install elinks
    package: name=elinks state=installed


